# Generated by Django 5.2.6 on 2025-09-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0002_cliente_produto_categoria_produto_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('eletronicos', 'Eletrônicos'), ('roupas', 'Roupas'), ('alimentos', 'Alimentos'), ('outros', 'Outros')], max_length=50),
        ),
    ]
