# Generated by Django 5.2.6 on 2025-09-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0003_alter_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cor',
            field=models.CharField(choices=[('Preto', 'Preto'), ('Branco', 'Branco'), ('Azul', 'Azul'), ('Cinza', 'Cinza'), ('Vinho', 'Vinho')], default='SEM COR', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Eletronicos', 'Eletrônicos'), ('Roupas', 'Roupas'), ('Alimentos', 'Alimentos'), ('Outros', 'Outros')], max_length=50),
        ),
    ]
